// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tradepb.proto

package tradepb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trade_Type int32

const (
	Trade_BUY  Trade_Type = 0
	Trade_SELL Trade_Type = 1
)

var Trade_Type_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}

var Trade_Type_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x Trade_Type) String() string {
	return proto.EnumName(Trade_Type_name, int32(x))
}

func (Trade_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{0, 0}
}

type Trade struct {
	// @inject_tag: bson:"_id"
	XId string `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty" bson:"_id"`
	// @inject_tag: bson:"type"
	Type Trade_Type `protobuf:"varint,2,opt,name=type,proto3,enum=trade.Trade_Type" json:"type,omitempty" bson:"type"`
	// @inject_tag: bson:"market"
	Market string `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty" bson:"market"`
	// @inject_tag: bson:"price"
	Price float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty" bson:"price"`
	// @inject_tag: bson:"amount"
	Amount float32 `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty" bson:"amount"`
	// @inject_tag: bson:"fee"
	Fee float32 `protobuf:"fixed32,6,opt,name=fee,proto3" json:"fee,omitempty" bson:"fee"`
	// @inject_tag: bson:"total"
	Total float32 `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty" bson:"total"`
	// @inject_tag: bson:"fiat_ind"
	FiatInd bool `protobuf:"varint,8,opt,name=fiat_ind,json=fiatInd,proto3" json:"fiat_ind,omitempty" bson:"fiat_ind"`
	// @inject_tag: bson:"date"
	Date                 string   `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty" bson:"date"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{0}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *Trade) GetType() Trade_Type {
	if m != nil {
		return m.Type
	}
	return Trade_BUY
}

func (m *Trade) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Trade) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Trade) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Trade) GetFiatInd() bool {
	if m != nil {
		return m.FiatInd
	}
	return false
}

func (m *Trade) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type AddTradeRequest struct {
	Trade                *Trade   `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTradeRequest) Reset()         { *m = AddTradeRequest{} }
func (m *AddTradeRequest) String() string { return proto.CompactTextString(m) }
func (*AddTradeRequest) ProtoMessage()    {}
func (*AddTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{1}
}

func (m *AddTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTradeRequest.Unmarshal(m, b)
}
func (m *AddTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTradeRequest.Marshal(b, m, deterministic)
}
func (m *AddTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTradeRequest.Merge(m, src)
}
func (m *AddTradeRequest) XXX_Size() int {
	return xxx_messageInfo_AddTradeRequest.Size(m)
}
func (m *AddTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTradeRequest proto.InternalMessageInfo

func (m *AddTradeRequest) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

func (m *AddTradeRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type AddTradeResponse struct {
	TradeId              string   `protobuf:"bytes,1,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTradeResponse) Reset()         { *m = AddTradeResponse{} }
func (m *AddTradeResponse) String() string { return proto.CompactTextString(m) }
func (*AddTradeResponse) ProtoMessage()    {}
func (*AddTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{2}
}

func (m *AddTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTradeResponse.Unmarshal(m, b)
}
func (m *AddTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTradeResponse.Marshal(b, m, deterministic)
}
func (m *AddTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTradeResponse.Merge(m, src)
}
func (m *AddTradeResponse) XXX_Size() int {
	return xxx_messageInfo_AddTradeResponse.Size(m)
}
func (m *AddTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTradeResponse proto.InternalMessageInfo

func (m *AddTradeResponse) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

type DeleteTradeRequest struct {
	TradeId              string   `protobuf:"bytes,1,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTradeRequest) Reset()         { *m = DeleteTradeRequest{} }
func (m *DeleteTradeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTradeRequest) ProtoMessage()    {}
func (*DeleteTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{3}
}

func (m *DeleteTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTradeRequest.Unmarshal(m, b)
}
func (m *DeleteTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTradeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTradeRequest.Merge(m, src)
}
func (m *DeleteTradeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTradeRequest.Size(m)
}
func (m *DeleteTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTradeRequest proto.InternalMessageInfo

func (m *DeleteTradeRequest) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *DeleteTradeRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type DeleteTradeResponse struct {
	DeletedCount         int32    `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTradeResponse) Reset()         { *m = DeleteTradeResponse{} }
func (m *DeleteTradeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTradeResponse) ProtoMessage()    {}
func (*DeleteTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{4}
}

func (m *DeleteTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTradeResponse.Unmarshal(m, b)
}
func (m *DeleteTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTradeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTradeResponse.Merge(m, src)
}
func (m *DeleteTradeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTradeResponse.Size(m)
}
func (m *DeleteTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTradeResponse proto.InternalMessageInfo

func (m *DeleteTradeResponse) GetDeletedCount() int32 {
	if m != nil {
		return m.DeletedCount
	}
	return 0
}

type UpdateTradeRequest struct {
	TradeId              string   `protobuf:"bytes,1,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	Trade                *Trade   `protobuf:"bytes,3,opt,name=trade,proto3" json:"trade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTradeRequest) Reset()         { *m = UpdateTradeRequest{} }
func (m *UpdateTradeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTradeRequest) ProtoMessage()    {}
func (*UpdateTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{5}
}

func (m *UpdateTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTradeRequest.Unmarshal(m, b)
}
func (m *UpdateTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTradeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTradeRequest.Merge(m, src)
}
func (m *UpdateTradeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTradeRequest.Size(m)
}
func (m *UpdateTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTradeRequest proto.InternalMessageInfo

func (m *UpdateTradeRequest) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *UpdateTradeRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

func (m *UpdateTradeRequest) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

type UpdateTradeResponse struct {
	ModifiedCount        int32    `protobuf:"varint,1,opt,name=modifiedCount,proto3" json:"modifiedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTradeResponse) Reset()         { *m = UpdateTradeResponse{} }
func (m *UpdateTradeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTradeResponse) ProtoMessage()    {}
func (*UpdateTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{6}
}

func (m *UpdateTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTradeResponse.Unmarshal(m, b)
}
func (m *UpdateTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTradeResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTradeResponse.Merge(m, src)
}
func (m *UpdateTradeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTradeResponse.Size(m)
}
func (m *UpdateTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTradeResponse proto.InternalMessageInfo

func (m *UpdateTradeResponse) GetModifiedCount() int32 {
	if m != nil {
		return m.ModifiedCount
	}
	return 0
}

type GetTradeRequest struct {
	TradeId              string   `protobuf:"bytes,1,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTradeRequest) Reset()         { *m = GetTradeRequest{} }
func (m *GetTradeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTradeRequest) ProtoMessage()    {}
func (*GetTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{7}
}

func (m *GetTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradeRequest.Unmarshal(m, b)
}
func (m *GetTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradeRequest.Marshal(b, m, deterministic)
}
func (m *GetTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradeRequest.Merge(m, src)
}
func (m *GetTradeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTradeRequest.Size(m)
}
func (m *GetTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradeRequest proto.InternalMessageInfo

func (m *GetTradeRequest) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *GetTradeRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type GetTradeResponse struct {
	Trade                *Trade   `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTradeResponse) Reset()         { *m = GetTradeResponse{} }
func (m *GetTradeResponse) String() string { return proto.CompactTextString(m) }
func (*GetTradeResponse) ProtoMessage()    {}
func (*GetTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{8}
}

func (m *GetTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradeResponse.Unmarshal(m, b)
}
func (m *GetTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradeResponse.Marshal(b, m, deterministic)
}
func (m *GetTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradeResponse.Merge(m, src)
}
func (m *GetTradeResponse) XXX_Size() int {
	return xxx_messageInfo_GetTradeResponse.Size(m)
}
func (m *GetTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradeResponse proto.InternalMessageInfo

func (m *GetTradeResponse) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

type GetAllTradesRequest struct {
	PortfolioId          int32    `protobuf:"varint,1,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTradesRequest) Reset()         { *m = GetAllTradesRequest{} }
func (m *GetAllTradesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllTradesRequest) ProtoMessage()    {}
func (*GetAllTradesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{9}
}

func (m *GetAllTradesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTradesRequest.Unmarshal(m, b)
}
func (m *GetAllTradesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTradesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllTradesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTradesRequest.Merge(m, src)
}
func (m *GetAllTradesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllTradesRequest.Size(m)
}
func (m *GetAllTradesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTradesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTradesRequest proto.InternalMessageInfo

func (m *GetAllTradesRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type GetAllTradesResponse struct {
	Trade                *Trade   `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTradesResponse) Reset()         { *m = GetAllTradesResponse{} }
func (m *GetAllTradesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllTradesResponse) ProtoMessage()    {}
func (*GetAllTradesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{10}
}

func (m *GetAllTradesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTradesResponse.Unmarshal(m, b)
}
func (m *GetAllTradesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTradesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllTradesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTradesResponse.Merge(m, src)
}
func (m *GetAllTradesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllTradesResponse.Size(m)
}
func (m *GetAllTradesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTradesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTradesResponse proto.InternalMessageInfo

func (m *GetAllTradesResponse) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

type ExportRequest struct {
	Trade                *Trade   `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportRequest) Reset()         { *m = ExportRequest{} }
func (m *ExportRequest) String() string { return proto.CompactTextString(m) }
func (*ExportRequest) ProtoMessage()    {}
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{11}
}

func (m *ExportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportRequest.Unmarshal(m, b)
}
func (m *ExportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportRequest.Marshal(b, m, deterministic)
}
func (m *ExportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportRequest.Merge(m, src)
}
func (m *ExportRequest) XXX_Size() int {
	return xxx_messageInfo_ExportRequest.Size(m)
}
func (m *ExportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportRequest proto.InternalMessageInfo

func (m *ExportRequest) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

func (m *ExportRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type ExportResponse struct {
	NumTrades            int32    `protobuf:"varint,1,opt,name=numTrades,proto3" json:"numTrades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportResponse) Reset()         { *m = ExportResponse{} }
func (m *ExportResponse) String() string { return proto.CompactTextString(m) }
func (*ExportResponse) ProtoMessage()    {}
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{12}
}

func (m *ExportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportResponse.Unmarshal(m, b)
}
func (m *ExportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportResponse.Marshal(b, m, deterministic)
}
func (m *ExportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportResponse.Merge(m, src)
}
func (m *ExportResponse) XXX_Size() int {
	return xxx_messageInfo_ExportResponse.Size(m)
}
func (m *ExportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportResponse proto.InternalMessageInfo

func (m *ExportResponse) GetNumTrades() int32 {
	if m != nil {
		return m.NumTrades
	}
	return 0
}

type ImportRequest struct {
	Trade                *Trade   `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	PortfolioId          int32    `protobuf:"varint,2,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{13}
}

func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (m *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(m, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetTrade() *Trade {
	if m != nil {
		return m.Trade
	}
	return nil
}

func (m *ImportRequest) GetPortfolioId() int32 {
	if m != nil {
		return m.PortfolioId
	}
	return 0
}

type ImportResponse struct {
	NumImported          int32    `protobuf:"varint,1,opt,name=numImported,proto3" json:"numImported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportResponse) Reset()         { *m = ImportResponse{} }
func (m *ImportResponse) String() string { return proto.CompactTextString(m) }
func (*ImportResponse) ProtoMessage()    {}
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c05b0caf8a109112, []int{14}
}

func (m *ImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResponse.Unmarshal(m, b)
}
func (m *ImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResponse.Marshal(b, m, deterministic)
}
func (m *ImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResponse.Merge(m, src)
}
func (m *ImportResponse) XXX_Size() int {
	return xxx_messageInfo_ImportResponse.Size(m)
}
func (m *ImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResponse proto.InternalMessageInfo

func (m *ImportResponse) GetNumImported() int32 {
	if m != nil {
		return m.NumImported
	}
	return 0
}

func init() {
	proto.RegisterEnum("trade.Trade_Type", Trade_Type_name, Trade_Type_value)
	proto.RegisterType((*Trade)(nil), "trade.Trade")
	proto.RegisterType((*AddTradeRequest)(nil), "trade.AddTradeRequest")
	proto.RegisterType((*AddTradeResponse)(nil), "trade.AddTradeResponse")
	proto.RegisterType((*DeleteTradeRequest)(nil), "trade.DeleteTradeRequest")
	proto.RegisterType((*DeleteTradeResponse)(nil), "trade.DeleteTradeResponse")
	proto.RegisterType((*UpdateTradeRequest)(nil), "trade.UpdateTradeRequest")
	proto.RegisterType((*UpdateTradeResponse)(nil), "trade.UpdateTradeResponse")
	proto.RegisterType((*GetTradeRequest)(nil), "trade.GetTradeRequest")
	proto.RegisterType((*GetTradeResponse)(nil), "trade.GetTradeResponse")
	proto.RegisterType((*GetAllTradesRequest)(nil), "trade.GetAllTradesRequest")
	proto.RegisterType((*GetAllTradesResponse)(nil), "trade.GetAllTradesResponse")
	proto.RegisterType((*ExportRequest)(nil), "trade.ExportRequest")
	proto.RegisterType((*ExportResponse)(nil), "trade.ExportResponse")
	proto.RegisterType((*ImportRequest)(nil), "trade.ImportRequest")
	proto.RegisterType((*ImportResponse)(nil), "trade.ImportResponse")
}

func init() { proto.RegisterFile("tradepb.proto", fileDescriptor_c05b0caf8a109112) }

var fileDescriptor_c05b0caf8a109112 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5b, 0x8b, 0x13, 0x4d,
	0x10, 0xcd, 0x64, 0x72, 0xad, 0x5c, 0xbf, 0x4a, 0xbe, 0x75, 0x32, 0xfa, 0x30, 0x34, 0x0a, 0x79,
	0x90, 0x20, 0x11, 0x94, 0x55, 0x7c, 0xd8, 0xd5, 0x75, 0x09, 0xae, 0x20, 0xb3, 0x1b, 0x44, 0x5f,
	0x96, 0x59, 0xbb, 0x03, 0x83, 0x99, 0x8b, 0x93, 0x8e, 0xb8, 0xbf, 0xd6, 0x9f, 0xe1, 0xab, 0x74,
	0x4f, 0xcf, 0x35, 0x59, 0x54, 0xc8, 0x4b, 0x98, 0x3a, 0xdd, 0xa7, 0xea, 0x54, 0xcd, 0xa9, 0x0c,
	0xf4, 0x78, 0xe4, 0x50, 0x16, 0xde, 0xcc, 0xc2, 0x28, 0xe0, 0x01, 0xd6, 0x65, 0x48, 0x7e, 0x69,
	0x50, 0xbf, 0x12, 0x4f, 0x38, 0x00, 0xfd, 0xda, 0xa5, 0x86, 0x66, 0x69, 0xd3, 0xb6, 0x5d, 0x5d,
	0x50, 0x7c, 0x04, 0x35, 0x7e, 0x1b, 0x32, 0xa3, 0x6a, 0x69, 0xd3, 0xfe, 0xfc, 0xbf, 0x99, 0x24,
	0xcc, 0xae, 0xe2, 0xdf, 0xdb, 0x90, 0xd9, 0xf2, 0x18, 0x8f, 0xa0, 0xe1, 0x39, 0xd1, 0x57, 0xc6,
	0x0d, 0x5d, 0x52, 0x55, 0x84, 0x63, 0xa8, 0x87, 0x91, 0xfb, 0x85, 0x19, 0x35, 0x4b, 0x9b, 0x56,
	0xed, 0x38, 0x10, 0xb7, 0x1d, 0x2f, 0xd8, 0xfa, 0xdc, 0xa8, 0x4b, 0x58, 0x45, 0x38, 0x04, 0x7d,
	0xc5, 0x98, 0xd1, 0x90, 0xa0, 0x78, 0x14, 0x7c, 0x1e, 0x70, 0x67, 0x6d, 0x34, 0x63, 0xbe, 0x0c,
	0x70, 0x02, 0xad, 0x95, 0xeb, 0xf0, 0x6b, 0xd7, 0xa7, 0x46, 0xcb, 0xd2, 0xa6, 0x2d, 0xbb, 0x29,
	0xe2, 0x85, 0x4f, 0x11, 0xa1, 0x46, 0x1d, 0xce, 0x8c, 0xb6, 0x94, 0x21, 0x9f, 0xc9, 0x04, 0x6a,
	0x42, 0x2a, 0x36, 0x41, 0x3f, 0x5d, 0x7e, 0x1a, 0x56, 0xb0, 0x05, 0xb5, 0xcb, 0xb3, 0x8b, 0x8b,
	0xa1, 0x46, 0x3e, 0xc2, 0xe0, 0x84, 0x52, 0xd9, 0x8e, 0xcd, 0xbe, 0x6d, 0xd9, 0x86, 0x23, 0x81,
	0x78, 0x2a, 0x72, 0x08, 0x9d, 0x79, 0x37, 0xdf, 0xb2, 0x1d, 0x1f, 0xa1, 0x05, 0x9d, 0x30, 0x88,
	0xf8, 0x2a, 0x58, 0xbb, 0xc1, 0x82, 0xca, 0xe1, 0xd4, 0xed, 0x3c, 0x44, 0x1e, 0xc3, 0x30, 0x4b,
	0xbc, 0x09, 0x03, 0x7f, 0xc3, 0xd0, 0x80, 0xa6, 0xa4, 0x2f, 0x92, 0x01, 0x27, 0x21, 0xf9, 0x00,
	0xf8, 0x86, 0xad, 0x19, 0x67, 0x05, 0x25, 0x77, 0xde, 0xff, 0x8b, 0xfa, 0xc7, 0x30, 0x2a, 0x64,
	0x54, 0x12, 0x08, 0x74, 0xa9, 0x84, 0xe9, 0x6b, 0x39, 0x7f, 0x4d, 0x32, 0x0b, 0x18, 0xe1, 0x80,
	0xcb, 0x50, 0x0c, 0xee, 0x50, 0x62, 0xb2, 0x91, 0xea, 0x77, 0x8e, 0x94, 0xbc, 0x84, 0x51, 0xa1,
	0xaa, 0x12, 0xfc, 0x10, 0x7a, 0x5e, 0x40, 0xdd, 0x95, 0x5b, 0x54, 0x5c, 0x04, 0xc9, 0x7b, 0x18,
	0x9c, 0x33, 0x7e, 0xb0, 0xe1, 0x3d, 0x83, 0x61, 0x96, 0x2e, 0x9d, 0xdc, 0x1f, 0x6d, 0x41, 0x9e,
	0xc3, 0xe8, 0x9c, 0xf1, 0x93, 0xf5, 0x5a, 0xa2, 0x9b, 0x44, 0x4a, 0xa9, 0xa0, 0xb6, 0x5b, 0xf0,
	0x05, 0x8c, 0x8b, 0xc4, 0x7f, 0x28, 0xba, 0x84, 0xde, 0xd9, 0x0f, 0x91, 0xec, 0xb0, 0x06, 0x9e,
	0x41, 0x3f, 0x49, 0xab, 0xc4, 0x3c, 0x80, 0xb6, 0xbf, 0xf5, 0x62, 0x85, 0xaa, 0x89, 0x0c, 0x10,
	0x32, 0x16, 0xde, 0xe1, 0x65, 0xcc, 0xa1, 0x9f, 0xa4, 0x55, 0x32, 0x2c, 0xe8, 0xf8, 0x5b, 0x2f,
	0x06, 0x59, 0x3a, 0xcd, 0x1c, 0x34, 0xff, 0xa9, 0x43, 0x57, 0x96, 0xb9, 0x64, 0xd1, 0x77, 0xf1,
	0x7f, 0xf3, 0x0a, 0x5a, 0xc9, 0x32, 0xe2, 0x91, 0xd2, 0x51, 0x5a, 0x7b, 0xf3, 0xde, 0x0e, 0x1e,
	0xd7, 0x23, 0x15, 0x7c, 0x0b, 0x9d, 0xdc, 0x2e, 0xe1, 0x44, 0xdd, 0xdc, 0xdd, 0x58, 0xd3, 0xdc,
	0x77, 0x94, 0xcf, 0x93, 0xb3, 0x78, 0x9a, 0x67, 0x77, 0xd9, 0xd2, 0x3c, 0x7b, 0x36, 0x82, 0x54,
	0x44, 0x3b, 0x89, 0x3d, 0xd3, 0x76, 0x4a, 0xf6, 0x4f, 0xdb, 0x29, 0xfb, 0x98, 0x54, 0xf0, 0x1d,
	0x74, 0xf3, 0x66, 0x43, 0x33, 0xbb, 0x5a, 0xb6, 0xae, 0x79, 0x7f, 0xef, 0x59, 0x92, 0xea, 0x89,
	0x86, 0xc7, 0xd0, 0x88, 0x6d, 0x82, 0x63, 0x75, 0xb5, 0x60, 0x46, 0xf3, 0xff, 0x12, 0x9a, 0x50,
	0xa7, 0x92, 0x1a, 0xbf, 0xb2, 0x94, 0x5a, 0x30, 0x50, 0x4a, 0x2d, 0xbe, 0x7f, 0x41, 0x3d, 0x6d,
	0x7f, 0x6e, 0xaa, 0x0f, 0xd9, 0x4d, 0x43, 0x7e, 0xc9, 0x9e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x39, 0xe8, 0xe6, 0xf4, 0xda, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradeServiceClient is the client API for TradeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradeServiceClient interface {
	AddTrade(ctx context.Context, in *AddTradeRequest, opts ...grpc.CallOption) (*AddTradeResponse, error)
	DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error)
	UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*UpdateTradeResponse, error)
	GetTrade(ctx context.Context, in *GetTradeRequest, opts ...grpc.CallOption) (*GetTradeResponse, error)
	GetAllTrades(ctx context.Context, in *GetAllTradesRequest, opts ...grpc.CallOption) (TradeService_GetAllTradesClient, error)
	Export(ctx context.Context, opts ...grpc.CallOption) (TradeService_ExportClient, error)
	Import(ctx context.Context, opts ...grpc.CallOption) (TradeService_ImportClient, error)
}

type tradeServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradeServiceClient(cc *grpc.ClientConn) TradeServiceClient {
	return &tradeServiceClient{cc}
}

func (c *tradeServiceClient) AddTrade(ctx context.Context, in *AddTradeRequest, opts ...grpc.CallOption) (*AddTradeResponse, error) {
	out := new(AddTradeResponse)
	err := c.cc.Invoke(ctx, "/trade.TradeService/AddTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*DeleteTradeResponse, error) {
	out := new(DeleteTradeResponse)
	err := c.cc.Invoke(ctx, "/trade.TradeService/DeleteTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*UpdateTradeResponse, error) {
	out := new(UpdateTradeResponse)
	err := c.cc.Invoke(ctx, "/trade.TradeService/UpdateTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetTrade(ctx context.Context, in *GetTradeRequest, opts ...grpc.CallOption) (*GetTradeResponse, error) {
	out := new(GetTradeResponse)
	err := c.cc.Invoke(ctx, "/trade.TradeService/GetTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetAllTrades(ctx context.Context, in *GetAllTradesRequest, opts ...grpc.CallOption) (TradeService_GetAllTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradeService_serviceDesc.Streams[0], "/trade.TradeService/GetAllTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradeServiceGetAllTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TradeService_GetAllTradesClient interface {
	Recv() (*GetAllTradesResponse, error)
	grpc.ClientStream
}

type tradeServiceGetAllTradesClient struct {
	grpc.ClientStream
}

func (x *tradeServiceGetAllTradesClient) Recv() (*GetAllTradesResponse, error) {
	m := new(GetAllTradesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradeServiceClient) Export(ctx context.Context, opts ...grpc.CallOption) (TradeService_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradeService_serviceDesc.Streams[1], "/trade.TradeService/Export", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradeServiceExportClient{stream}
	return x, nil
}

type TradeService_ExportClient interface {
	Send(*ExportRequest) error
	CloseAndRecv() (*ExportResponse, error)
	grpc.ClientStream
}

type tradeServiceExportClient struct {
	grpc.ClientStream
}

func (x *tradeServiceExportClient) Send(m *ExportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tradeServiceExportClient) CloseAndRecv() (*ExportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ExportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradeServiceClient) Import(ctx context.Context, opts ...grpc.CallOption) (TradeService_ImportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradeService_serviceDesc.Streams[2], "/trade.TradeService/Import", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradeServiceImportClient{stream}
	return x, nil
}

type TradeService_ImportClient interface {
	Send(*ImportRequest) error
	CloseAndRecv() (*ImportResponse, error)
	grpc.ClientStream
}

type tradeServiceImportClient struct {
	grpc.ClientStream
}

func (x *tradeServiceImportClient) Send(m *ImportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tradeServiceImportClient) CloseAndRecv() (*ImportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TradeServiceServer is the server API for TradeService service.
type TradeServiceServer interface {
	AddTrade(context.Context, *AddTradeRequest) (*AddTradeResponse, error)
	DeleteTrade(context.Context, *DeleteTradeRequest) (*DeleteTradeResponse, error)
	UpdateTrade(context.Context, *UpdateTradeRequest) (*UpdateTradeResponse, error)
	GetTrade(context.Context, *GetTradeRequest) (*GetTradeResponse, error)
	GetAllTrades(*GetAllTradesRequest, TradeService_GetAllTradesServer) error
	Export(TradeService_ExportServer) error
	Import(TradeService_ImportServer) error
}

// UnimplementedTradeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTradeServiceServer struct {
}

func (*UnimplementedTradeServiceServer) AddTrade(ctx context.Context, req *AddTradeRequest) (*AddTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTrade not implemented")
}
func (*UnimplementedTradeServiceServer) DeleteTrade(ctx context.Context, req *DeleteTradeRequest) (*DeleteTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrade not implemented")
}
func (*UnimplementedTradeServiceServer) UpdateTrade(ctx context.Context, req *UpdateTradeRequest) (*UpdateTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrade not implemented")
}
func (*UnimplementedTradeServiceServer) GetTrade(ctx context.Context, req *GetTradeRequest) (*GetTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrade not implemented")
}
func (*UnimplementedTradeServiceServer) GetAllTrades(req *GetAllTradesRequest, srv TradeService_GetAllTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllTrades not implemented")
}
func (*UnimplementedTradeServiceServer) Export(srv TradeService_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (*UnimplementedTradeServiceServer) Import(srv TradeService_ImportServer) error {
	return status.Errorf(codes.Unimplemented, "method Import not implemented")
}

func RegisterTradeServiceServer(s *grpc.Server, srv TradeServiceServer) {
	s.RegisterService(&_TradeService_serviceDesc, srv)
}

func _TradeService_AddTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).AddTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trade.TradeService/AddTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).AddTrade(ctx, req.(*AddTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_DeleteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).DeleteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trade.TradeService/DeleteTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).DeleteTrade(ctx, req.(*DeleteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_UpdateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).UpdateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trade.TradeService/UpdateTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).UpdateTrade(ctx, req.(*UpdateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).GetTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trade.TradeService/GetTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).GetTrade(ctx, req.(*GetTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetAllTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradeServiceServer).GetAllTrades(m, &tradeServiceGetAllTradesServer{stream})
}

type TradeService_GetAllTradesServer interface {
	Send(*GetAllTradesResponse) error
	grpc.ServerStream
}

type tradeServiceGetAllTradesServer struct {
	grpc.ServerStream
}

func (x *tradeServiceGetAllTradesServer) Send(m *GetAllTradesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TradeService_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradeServiceServer).Export(&tradeServiceExportServer{stream})
}

type TradeService_ExportServer interface {
	SendAndClose(*ExportResponse) error
	Recv() (*ExportRequest, error)
	grpc.ServerStream
}

type tradeServiceExportServer struct {
	grpc.ServerStream
}

func (x *tradeServiceExportServer) SendAndClose(m *ExportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tradeServiceExportServer) Recv() (*ExportRequest, error) {
	m := new(ExportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TradeService_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradeServiceServer).Import(&tradeServiceImportServer{stream})
}

type TradeService_ImportServer interface {
	SendAndClose(*ImportResponse) error
	Recv() (*ImportRequest, error)
	grpc.ServerStream
}

type tradeServiceImportServer struct {
	grpc.ServerStream
}

func (x *tradeServiceImportServer) SendAndClose(m *ImportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tradeServiceImportServer) Recv() (*ImportRequest, error) {
	m := new(ImportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TradeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trade.TradeService",
	HandlerType: (*TradeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTrade",
			Handler:    _TradeService_AddTrade_Handler,
		},
		{
			MethodName: "DeleteTrade",
			Handler:    _TradeService_DeleteTrade_Handler,
		},
		{
			MethodName: "UpdateTrade",
			Handler:    _TradeService_UpdateTrade_Handler,
		},
		{
			MethodName: "GetTrade",
			Handler:    _TradeService_GetTrade_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllTrades",
			Handler:       _TradeService_GetAllTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Export",
			Handler:       _TradeService_Export_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Import",
			Handler:       _TradeService_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tradepb.proto",
}
